# Generated by Django 5.2.7 on 2025-10-16 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transitrack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('numero_licencia', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='ruta',
            name='horario',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='ruta',
            name='conductor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transitrack.conductor'),
        ),
    ]
